name: cpr-reputation
channels:
    - anaconda
    - conda-forge
    - pytorch
dependencies:
    - python=3.8
    - numpy=1.19.2
    - scipy=1.6.1
    - numba=0.53.0
    - matplotlib=3.3.4
    - pytorch=1.8.1
    - ray-rllib=1.1.0
    - black
    - flake8
    - pytest
    - hypothesis
    - pytype
    - ninja
