name: cpr-reputation
channels:
    - anaconda
    - conda-forge
    - pytorch
dependencies:
    - python=3.8
    - scipy=1.6.1
    - numba=0.53.0
    - matplotlib=3.3.4
    - pytorch=1.8.1
    - black
    - flake8
    - pytest
    - hypothesis
    - pytype
    - ninja
    - pip
    - pip:
        - ray[rllib]==1.2.0
        - numpy==1.20.1
