name: cpr-reputation
channels:
    - defaults
dependencies:
    - python=3.8
    - numpy=1.20.1
    - scipy=1.6.1
    - numba=0.53.0
    - matplotlib=3.3.4
    - black
    - flake8
    - pytest
    - hypothesis
    - pytype
