---
env_config:
  num_agents: 1
  size: !!python/tuple [26, 9]
  sight_width: 5
  sight_dist: 10
  num_crosses: 9
  apple_values_method:
  tagging_values_method:
  sustainability_metric: deepmind
ray_config:
  framework: torch
  train_batch_size: 4000
  rollout_fragment_length: 1000
  sgd_minibatch_size: 512
  num_sgd_iter: 3
  lambda: 0.92
  kl_coeff: 0.2
  lr: 1.0e-5
  vf_loss_coeff: 1.0e-2
  gamma: 0.99
run_config:
  heterogeneous: true
  verbose: true
  wandb_key_file: WANDB_TOKEN
